//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ImproperPaymentV2.SSI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SecuritySoap", Namespace="http://146.243.13.169/SSO_WS/")]
    public partial class Security : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsGoodEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsGoodUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsGoodPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsGoodPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSessionHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSessionIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfile1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfile2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserProfile_MultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewSsiUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewSsiUser1OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSsiUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartNewSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartNewSession1OperationCompleted;
        
        private System.Threading.SendOrPostCallback StartNewSessionByUsernamePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeActivateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserID1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserAppsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsSsiUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsSsiUser1OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Security() {
            this.Url = global::ImproperPaymentV2.Properties.Settings.Default.ImproperPaymentV2_SSI_Security;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsGoodEmailAddressCompletedEventHandler IsGoodEmailAddressCompleted;
        
        /// <remarks/>
        public event IsGoodUserNameCompletedEventHandler IsGoodUserNameCompleted;
        
        /// <remarks/>
        public event IsGoodPasswordCompletedEventHandler IsGoodPasswordCompleted;
        
        /// <remarks/>
        public event IsGoodPhoneNumberCompletedEventHandler IsGoodPhoneNumberCompleted;
        
        /// <remarks/>
        public event UpdateSessionHistoryCompletedEventHandler UpdateSessionHistoryCompleted;
        
        /// <remarks/>
        public event GetSessionIdCompletedEventHandler GetSessionIdCompleted;
        
        /// <remarks/>
        public event IsValidSessionCompletedEventHandler IsValidSessionCompleted;
        
        /// <remarks/>
        public event GetUserProfileCompletedEventHandler GetUserProfileCompleted;
        
        /// <remarks/>
        public event GetUserProfile1CompletedEventHandler GetUserProfile1Completed;
        
        /// <remarks/>
        public event GetUserProfile2CompletedEventHandler GetUserProfile2Completed;
        
        /// <remarks/>
        public event GetUserProfile_MultipleCompletedEventHandler GetUserProfile_MultipleCompleted;
        
        /// <remarks/>
        public event AddNewSsiUserCompletedEventHandler AddNewSsiUserCompleted;
        
        /// <remarks/>
        public event AddNewSsiUser1CompletedEventHandler AddNewSsiUser1Completed;
        
        /// <remarks/>
        public event UpdateSsiUserCompletedEventHandler UpdateSsiUserCompleted;
        
        /// <remarks/>
        public event StartNewSessionCompletedEventHandler StartNewSessionCompleted;
        
        /// <remarks/>
        public event StartNewSession1CompletedEventHandler StartNewSession1Completed;
        
        /// <remarks/>
        public event StartNewSessionByUsernamePasswordCompletedEventHandler StartNewSessionByUsernamePasswordCompleted;
        
        /// <remarks/>
        public event EndSessionCompletedEventHandler EndSessionCompleted;
        
        /// <remarks/>
        public event DeActivateUserCompletedEventHandler DeActivateUserCompleted;
        
        /// <remarks/>
        public event ActivateUserCompletedEventHandler ActivateUserCompleted;
        
        /// <remarks/>
        public event GetUserIDCompletedEventHandler GetUserIDCompleted;
        
        /// <remarks/>
        public event GetUserID1CompletedEventHandler GetUserID1Completed;
        
        /// <remarks/>
        public event GetUserNameCompletedEventHandler GetUserNameCompleted;
        
        /// <remarks/>
        public event GetUserAppsInfoCompletedEventHandler GetUserAppsInfoCompleted;
        
        /// <remarks/>
        public event IsSsiUserCompletedEventHandler IsSsiUserCompleted;
        
        /// <remarks/>
        public event IsSsiUser1CompletedEventHandler IsSsiUser1Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsGoodEmailAddress", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsGoodEmailAddress(string email) {
            object[] results = this.Invoke("IsGoodEmailAddress", new object[] {
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsGoodEmailAddressAsync(string email) {
            this.IsGoodEmailAddressAsync(email, null);
        }
        
        /// <remarks/>
        public void IsGoodEmailAddressAsync(string email, object userState) {
            if ((this.IsGoodEmailAddressOperationCompleted == null)) {
                this.IsGoodEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsGoodEmailAddressOperationCompleted);
            }
            this.InvokeAsync("IsGoodEmailAddress", new object[] {
                        email}, this.IsGoodEmailAddressOperationCompleted, userState);
        }
        
        private void OnIsGoodEmailAddressOperationCompleted(object arg) {
            if ((this.IsGoodEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsGoodEmailAddressCompleted(this, new IsGoodEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsGoodUserName", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsGoodUserName(string userName) {
            object[] results = this.Invoke("IsGoodUserName", new object[] {
                        userName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsGoodUserNameAsync(string userName) {
            this.IsGoodUserNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void IsGoodUserNameAsync(string userName, object userState) {
            if ((this.IsGoodUserNameOperationCompleted == null)) {
                this.IsGoodUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsGoodUserNameOperationCompleted);
            }
            this.InvokeAsync("IsGoodUserName", new object[] {
                        userName}, this.IsGoodUserNameOperationCompleted, userState);
        }
        
        private void OnIsGoodUserNameOperationCompleted(object arg) {
            if ((this.IsGoodUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsGoodUserNameCompleted(this, new IsGoodUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsGoodPassword", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsGoodPassword(string password) {
            object[] results = this.Invoke("IsGoodPassword", new object[] {
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsGoodPasswordAsync(string password) {
            this.IsGoodPasswordAsync(password, null);
        }
        
        /// <remarks/>
        public void IsGoodPasswordAsync(string password, object userState) {
            if ((this.IsGoodPasswordOperationCompleted == null)) {
                this.IsGoodPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsGoodPasswordOperationCompleted);
            }
            this.InvokeAsync("IsGoodPassword", new object[] {
                        password}, this.IsGoodPasswordOperationCompleted, userState);
        }
        
        private void OnIsGoodPasswordOperationCompleted(object arg) {
            if ((this.IsGoodPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsGoodPasswordCompleted(this, new IsGoodPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsGoodPhoneNumber", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsGoodPhoneNumber(string phone) {
            object[] results = this.Invoke("IsGoodPhoneNumber", new object[] {
                        phone});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsGoodPhoneNumberAsync(string phone) {
            this.IsGoodPhoneNumberAsync(phone, null);
        }
        
        /// <remarks/>
        public void IsGoodPhoneNumberAsync(string phone, object userState) {
            if ((this.IsGoodPhoneNumberOperationCompleted == null)) {
                this.IsGoodPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsGoodPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("IsGoodPhoneNumber", new object[] {
                        phone}, this.IsGoodPhoneNumberOperationCompleted, userState);
        }
        
        private void OnIsGoodPhoneNumberOperationCompleted(object arg) {
            if ((this.IsGoodPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsGoodPhoneNumberCompleted(this, new IsGoodPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/UpdateSessionHistory", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateSessionHistory(string sessionID, EECApp requestorApp, string requestedPageUrl) {
            this.Invoke("UpdateSessionHistory", new object[] {
                        sessionID,
                        requestorApp,
                        requestedPageUrl});
        }
        
        /// <remarks/>
        public void UpdateSessionHistoryAsync(string sessionID, EECApp requestorApp, string requestedPageUrl) {
            this.UpdateSessionHistoryAsync(sessionID, requestorApp, requestedPageUrl, null);
        }
        
        /// <remarks/>
        public void UpdateSessionHistoryAsync(string sessionID, EECApp requestorApp, string requestedPageUrl, object userState) {
            if ((this.UpdateSessionHistoryOperationCompleted == null)) {
                this.UpdateSessionHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSessionHistoryOperationCompleted);
            }
            this.InvokeAsync("UpdateSessionHistory", new object[] {
                        sessionID,
                        requestorApp,
                        requestedPageUrl}, this.UpdateSessionHistoryOperationCompleted, userState);
        }
        
        private void OnUpdateSessionHistoryOperationCompleted(object arg) {
            if ((this.UpdateSessionHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSessionHistoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetSessionId", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSessionId(string iTicket) {
            object[] results = this.Invoke("GetSessionId", new object[] {
                        iTicket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSessionIdAsync(string iTicket) {
            this.GetSessionIdAsync(iTicket, null);
        }
        
        /// <remarks/>
        public void GetSessionIdAsync(string iTicket, object userState) {
            if ((this.GetSessionIdOperationCompleted == null)) {
                this.GetSessionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSessionIdOperationCompleted);
            }
            this.InvokeAsync("GetSessionId", new object[] {
                        iTicket}, this.GetSessionIdOperationCompleted, userState);
        }
        
        private void OnGetSessionIdOperationCompleted(object arg) {
            if ((this.GetSessionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSessionIdCompleted(this, new GetSessionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsValidSession", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidSession(string sessionID) {
            object[] results = this.Invoke("IsValidSession", new object[] {
                        sessionID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidSessionAsync(string sessionID) {
            this.IsValidSessionAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void IsValidSessionAsync(string sessionID, object userState) {
            if ((this.IsValidSessionOperationCompleted == null)) {
                this.IsValidSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidSessionOperationCompleted);
            }
            this.InvokeAsync("IsValidSession", new object[] {
                        sessionID}, this.IsValidSessionOperationCompleted, userState);
        }
        
        private void OnIsValidSessionOperationCompleted(object arg) {
            if ((this.IsValidSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidSessionCompleted(this, new IsValidSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserProfile1", RequestElementName="GetUserProfile1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserProfile1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserProfile1Result")]
        public System.Data.DataSet GetUserProfile(string sessionID) {
            object[] results = this.Invoke("GetUserProfile", new object[] {
                        sessionID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfileAsync(string sessionID) {
            this.GetUserProfileAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void GetUserProfileAsync(string sessionID, object userState) {
            if ((this.GetUserProfileOperationCompleted == null)) {
                this.GetUserProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfileOperationCompleted);
            }
            this.InvokeAsync("GetUserProfile", new object[] {
                        sessionID}, this.GetUserProfileOperationCompleted, userState);
        }
        
        private void OnGetUserProfileOperationCompleted(object arg) {
            if ((this.GetUserProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfileCompleted(this, new GetUserProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetUserProfile1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserProfile2", RequestElementName="GetUserProfile2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserProfile2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserProfile2Result")]
        public System.Data.DataSet GetUserProfile(string sessionID, string userName) {
            object[] results = this.Invoke("GetUserProfile1", new object[] {
                        sessionID,
                        userName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfile1Async(string sessionID, string userName) {
            this.GetUserProfile1Async(sessionID, userName, null);
        }
        
        /// <remarks/>
        public void GetUserProfile1Async(string sessionID, string userName, object userState) {
            if ((this.GetUserProfile1OperationCompleted == null)) {
                this.GetUserProfile1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfile1OperationCompleted);
            }
            this.InvokeAsync("GetUserProfile1", new object[] {
                        sessionID,
                        userName}, this.GetUserProfile1OperationCompleted, userState);
        }
        
        private void OnGetUserProfile1OperationCompleted(object arg) {
            if ((this.GetUserProfile1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfile1Completed(this, new GetUserProfile1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetUserProfile2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserProfile3", RequestElementName="GetUserProfile3", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserProfile3Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserProfile3Result")]
        public System.Data.DataSet GetUserProfile(string sessionID, int userID) {
            object[] results = this.Invoke("GetUserProfile2", new object[] {
                        sessionID,
                        userID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfile2Async(string sessionID, int userID) {
            this.GetUserProfile2Async(sessionID, userID, null);
        }
        
        /// <remarks/>
        public void GetUserProfile2Async(string sessionID, int userID, object userState) {
            if ((this.GetUserProfile2OperationCompleted == null)) {
                this.GetUserProfile2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfile2OperationCompleted);
            }
            this.InvokeAsync("GetUserProfile2", new object[] {
                        sessionID,
                        userID}, this.GetUserProfile2OperationCompleted, userState);
        }
        
        private void OnGetUserProfile2OperationCompleted(object arg) {
            if ((this.GetUserProfile2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfile2Completed(this, new GetUserProfile2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserProfile_Multiple", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserProfile_Multiple(string sessionID, string userIDList) {
            object[] results = this.Invoke("GetUserProfile_Multiple", new object[] {
                        sessionID,
                        userIDList});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserProfile_MultipleAsync(string sessionID, string userIDList) {
            this.GetUserProfile_MultipleAsync(sessionID, userIDList, null);
        }
        
        /// <remarks/>
        public void GetUserProfile_MultipleAsync(string sessionID, string userIDList, object userState) {
            if ((this.GetUserProfile_MultipleOperationCompleted == null)) {
                this.GetUserProfile_MultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserProfile_MultipleOperationCompleted);
            }
            this.InvokeAsync("GetUserProfile_Multiple", new object[] {
                        sessionID,
                        userIDList}, this.GetUserProfile_MultipleOperationCompleted, userState);
        }
        
        private void OnGetUserProfile_MultipleOperationCompleted(object arg) {
            if ((this.GetUserProfile_MultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserProfile_MultipleCompleted(this, new GetUserProfile_MultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/AddNewSsiUser1", RequestElementName="AddNewSsiUser1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="AddNewSsiUser1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddNewSsiUser1Result")]
        public int AddNewSsiUser(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    EECApp applicationName) {
            object[] results = this.Invoke("AddNewSsiUser", new object[] {
                        sessionID,
                        userName,
                        ssoPassword,
                        securityPhrase,
                        firstName,
                        lastName,
                        gender,
                        dayOfBirthMonth,
                        phone,
                        phoneExt,
                        email,
                        secQuestionID,
                        secAnswer,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        termsConditionsAccepted,
                        ssoStatus,
                        createdByUserID,
                        applicationName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewSsiUserAsync(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    EECApp applicationName) {
            this.AddNewSsiUserAsync(sessionID, userName, ssoPassword, securityPhrase, firstName, lastName, gender, dayOfBirthMonth, phone, phoneExt, email, secQuestionID, secAnswer, streetAddress, streetAddress2, city, state, zip, termsConditionsAccepted, ssoStatus, createdByUserID, applicationName, null);
        }
        
        /// <remarks/>
        public void AddNewSsiUserAsync(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    EECApp applicationName, 
                    object userState) {
            if ((this.AddNewSsiUserOperationCompleted == null)) {
                this.AddNewSsiUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewSsiUserOperationCompleted);
            }
            this.InvokeAsync("AddNewSsiUser", new object[] {
                        sessionID,
                        userName,
                        ssoPassword,
                        securityPhrase,
                        firstName,
                        lastName,
                        gender,
                        dayOfBirthMonth,
                        phone,
                        phoneExt,
                        email,
                        secQuestionID,
                        secAnswer,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        termsConditionsAccepted,
                        ssoStatus,
                        createdByUserID,
                        applicationName}, this.AddNewSsiUserOperationCompleted, userState);
        }
        
        private void OnAddNewSsiUserOperationCompleted(object arg) {
            if ((this.AddNewSsiUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewSsiUserCompleted(this, new AddNewSsiUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="AddNewSsiUser1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/AddNewSsiUser2", RequestElementName="AddNewSsiUser2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="AddNewSsiUser2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddNewSsiUser2Result")]
        public int AddNewSsiUser(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    int applicationId) {
            object[] results = this.Invoke("AddNewSsiUser1", new object[] {
                        sessionID,
                        userName,
                        ssoPassword,
                        securityPhrase,
                        firstName,
                        lastName,
                        gender,
                        dayOfBirthMonth,
                        phone,
                        phoneExt,
                        email,
                        secQuestionID,
                        secAnswer,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        termsConditionsAccepted,
                        ssoStatus,
                        createdByUserID,
                        applicationId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewSsiUser1Async(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    int applicationId) {
            this.AddNewSsiUser1Async(sessionID, userName, ssoPassword, securityPhrase, firstName, lastName, gender, dayOfBirthMonth, phone, phoneExt, email, secQuestionID, secAnswer, streetAddress, streetAddress2, city, state, zip, termsConditionsAccepted, ssoStatus, createdByUserID, applicationId, null);
        }
        
        /// <remarks/>
        public void AddNewSsiUser1Async(
                    string sessionID, 
                    string userName, 
                    string ssoPassword, 
                    string securityPhrase, 
                    string firstName, 
                    string lastName, 
                    Gender gender, 
                    int dayOfBirthMonth, 
                    string phone, 
                    string phoneExt, 
                    string email, 
                    int secQuestionID, 
                    string secAnswer, 
                    string streetAddress, 
                    string streetAddress2, 
                    string city, 
                    string state, 
                    string zip, 
                    TermsConditions termsConditionsAccepted, 
                    SSOStatus ssoStatus, 
                    int createdByUserID, 
                    int applicationId, 
                    object userState) {
            if ((this.AddNewSsiUser1OperationCompleted == null)) {
                this.AddNewSsiUser1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewSsiUser1OperationCompleted);
            }
            this.InvokeAsync("AddNewSsiUser1", new object[] {
                        sessionID,
                        userName,
                        ssoPassword,
                        securityPhrase,
                        firstName,
                        lastName,
                        gender,
                        dayOfBirthMonth,
                        phone,
                        phoneExt,
                        email,
                        secQuestionID,
                        secAnswer,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        termsConditionsAccepted,
                        ssoStatus,
                        createdByUserID,
                        applicationId}, this.AddNewSsiUser1OperationCompleted, userState);
        }
        
        private void OnAddNewSsiUser1OperationCompleted(object arg) {
            if ((this.AddNewSsiUser1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewSsiUser1Completed(this, new AddNewSsiUser1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/UpdateSsiUser", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateSsiUser(string sessionID, int userID, string firstName, string lastName, Gender gender, string phone, string phoneExt, string email, string streetAddress, string streetAddress2, string city, string state, string zip, int modifyByUserId) {
            object[] results = this.Invoke("UpdateSsiUser", new object[] {
                        sessionID,
                        userID,
                        firstName,
                        lastName,
                        gender,
                        phone,
                        phoneExt,
                        email,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        modifyByUserId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSsiUserAsync(string sessionID, int userID, string firstName, string lastName, Gender gender, string phone, string phoneExt, string email, string streetAddress, string streetAddress2, string city, string state, string zip, int modifyByUserId) {
            this.UpdateSsiUserAsync(sessionID, userID, firstName, lastName, gender, phone, phoneExt, email, streetAddress, streetAddress2, city, state, zip, modifyByUserId, null);
        }
        
        /// <remarks/>
        public void UpdateSsiUserAsync(string sessionID, int userID, string firstName, string lastName, Gender gender, string phone, string phoneExt, string email, string streetAddress, string streetAddress2, string city, string state, string zip, int modifyByUserId, object userState) {
            if ((this.UpdateSsiUserOperationCompleted == null)) {
                this.UpdateSsiUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSsiUserOperationCompleted);
            }
            this.InvokeAsync("UpdateSsiUser", new object[] {
                        sessionID,
                        userID,
                        firstName,
                        lastName,
                        gender,
                        phone,
                        phoneExt,
                        email,
                        streetAddress,
                        streetAddress2,
                        city,
                        state,
                        zip,
                        modifyByUserId}, this.UpdateSsiUserOperationCompleted, userState);
        }
        
        private void OnUpdateSsiUserOperationCompleted(object arg) {
            if ((this.UpdateSsiUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSsiUserCompleted(this, new UpdateSsiUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/StartNewSession1", RequestElementName="StartNewSession1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="StartNewSession1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StartNewSession1Result")]
        public string StartNewSession(int userID, string identityToken) {
            object[] results = this.Invoke("StartNewSession", new object[] {
                        userID,
                        identityToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartNewSessionAsync(int userID, string identityToken) {
            this.StartNewSessionAsync(userID, identityToken, null);
        }
        
        /// <remarks/>
        public void StartNewSessionAsync(int userID, string identityToken, object userState) {
            if ((this.StartNewSessionOperationCompleted == null)) {
                this.StartNewSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartNewSessionOperationCompleted);
            }
            this.InvokeAsync("StartNewSession", new object[] {
                        userID,
                        identityToken}, this.StartNewSessionOperationCompleted, userState);
        }
        
        private void OnStartNewSessionOperationCompleted(object arg) {
            if ((this.StartNewSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartNewSessionCompleted(this, new StartNewSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="StartNewSession1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/StartNewSession2", RequestElementName="StartNewSession2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="StartNewSession2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StartNewSession2Result")]
        public string StartNewSession(string userName, string identityToken) {
            object[] results = this.Invoke("StartNewSession1", new object[] {
                        userName,
                        identityToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartNewSession1Async(string userName, string identityToken) {
            this.StartNewSession1Async(userName, identityToken, null);
        }
        
        /// <remarks/>
        public void StartNewSession1Async(string userName, string identityToken, object userState) {
            if ((this.StartNewSession1OperationCompleted == null)) {
                this.StartNewSession1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartNewSession1OperationCompleted);
            }
            this.InvokeAsync("StartNewSession1", new object[] {
                        userName,
                        identityToken}, this.StartNewSession1OperationCompleted, userState);
        }
        
        private void OnStartNewSession1OperationCompleted(object arg) {
            if ((this.StartNewSession1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartNewSession1Completed(this, new StartNewSession1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/StartNewSessionByLoginDetails", RequestElementName="StartNewSessionByLoginDetails", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="StartNewSessionByLoginDetailsResponse", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StartNewSessionByLoginDetailsResult")]
        public string StartNewSessionByUsernamePassword(string userName, string password) {
            object[] results = this.Invoke("StartNewSessionByUsernamePassword", new object[] {
                        userName,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartNewSessionByUsernamePasswordAsync(string userName, string password) {
            this.StartNewSessionByUsernamePasswordAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void StartNewSessionByUsernamePasswordAsync(string userName, string password, object userState) {
            if ((this.StartNewSessionByUsernamePasswordOperationCompleted == null)) {
                this.StartNewSessionByUsernamePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartNewSessionByUsernamePasswordOperationCompleted);
            }
            this.InvokeAsync("StartNewSessionByUsernamePassword", new object[] {
                        userName,
                        password}, this.StartNewSessionByUsernamePasswordOperationCompleted, userState);
        }
        
        private void OnStartNewSessionByUsernamePasswordOperationCompleted(object arg) {
            if ((this.StartNewSessionByUsernamePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartNewSessionByUsernamePasswordCompleted(this, new StartNewSessionByUsernamePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/EndSession", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EndSession(string sessionID) {
            object[] results = this.Invoke("EndSession", new object[] {
                        sessionID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EndSessionAsync(string sessionID) {
            this.EndSessionAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void EndSessionAsync(string sessionID, object userState) {
            if ((this.EndSessionOperationCompleted == null)) {
                this.EndSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndSessionOperationCompleted);
            }
            this.InvokeAsync("EndSession", new object[] {
                        sessionID}, this.EndSessionOperationCompleted, userState);
        }
        
        private void OnEndSessionOperationCompleted(object arg) {
            if ((this.EndSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndSessionCompleted(this, new EndSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/DeActivateUser1", RequestElementName="DeActivateUser1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="DeActivateUser1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeActivateUser1Result")]
        public int DeActivateUser(string sessionID, int userID, EECApp userApps) {
            object[] results = this.Invoke("DeActivateUser", new object[] {
                        sessionID,
                        userID,
                        userApps});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeActivateUserAsync(string sessionID, int userID, EECApp userApps) {
            this.DeActivateUserAsync(sessionID, userID, userApps, null);
        }
        
        /// <remarks/>
        public void DeActivateUserAsync(string sessionID, int userID, EECApp userApps, object userState) {
            if ((this.DeActivateUserOperationCompleted == null)) {
                this.DeActivateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeActivateUserOperationCompleted);
            }
            this.InvokeAsync("DeActivateUser", new object[] {
                        sessionID,
                        userID,
                        userApps}, this.DeActivateUserOperationCompleted, userState);
        }
        
        private void OnDeActivateUserOperationCompleted(object arg) {
            if ((this.DeActivateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeActivateUserCompleted(this, new DeActivateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/ActivateUser1", RequestElementName="ActivateUser1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="ActivateUser1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ActivateUser1Result")]
        public int ActivateUser(string sessionID, int userID, EECApp eecApplication) {
            object[] results = this.Invoke("ActivateUser", new object[] {
                        sessionID,
                        userID,
                        eecApplication});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateUserAsync(string sessionID, int userID, EECApp eecApplication) {
            this.ActivateUserAsync(sessionID, userID, eecApplication, null);
        }
        
        /// <remarks/>
        public void ActivateUserAsync(string sessionID, int userID, EECApp eecApplication, object userState) {
            if ((this.ActivateUserOperationCompleted == null)) {
                this.ActivateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateUserOperationCompleted);
            }
            this.InvokeAsync("ActivateUser", new object[] {
                        sessionID,
                        userID,
                        eecApplication}, this.ActivateUserOperationCompleted, userState);
        }
        
        private void OnActivateUserOperationCompleted(object arg) {
            if ((this.ActivateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateUserCompleted(this, new ActivateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserID1", RequestElementName="GetUserID1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserID1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserID1Result")]
        public int GetUserID(string sessionID) {
            object[] results = this.Invoke("GetUserID", new object[] {
                        sessionID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserIDAsync(string sessionID) {
            this.GetUserIDAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void GetUserIDAsync(string sessionID, object userState) {
            if ((this.GetUserIDOperationCompleted == null)) {
                this.GetUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserIDOperationCompleted);
            }
            this.InvokeAsync("GetUserID", new object[] {
                        sessionID}, this.GetUserIDOperationCompleted, userState);
        }
        
        private void OnGetUserIDOperationCompleted(object arg) {
            if ((this.GetUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserIDCompleted(this, new GetUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="GetUserID1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserID2", RequestElementName="GetUserID2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserID2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserID2Result")]
        public int GetUserID(string sessionID, string userName) {
            object[] results = this.Invoke("GetUserID1", new object[] {
                        sessionID,
                        userName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserID1Async(string sessionID, string userName) {
            this.GetUserID1Async(sessionID, userName, null);
        }
        
        /// <remarks/>
        public void GetUserID1Async(string sessionID, string userName, object userState) {
            if ((this.GetUserID1OperationCompleted == null)) {
                this.GetUserID1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserID1OperationCompleted);
            }
            this.InvokeAsync("GetUserID1", new object[] {
                        sessionID,
                        userName}, this.GetUserID1OperationCompleted, userState);
        }
        
        private void OnGetUserID1OperationCompleted(object arg) {
            if ((this.GetUserID1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserID1Completed(this, new GetUserID1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserName2", RequestElementName="GetUserName2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserName2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserName2Result")]
        public string GetUserName(string sessionID, int userID) {
            object[] results = this.Invoke("GetUserName", new object[] {
                        sessionID,
                        userID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string sessionID, int userID) {
            this.GetUserNameAsync(sessionID, userID, null);
        }
        
        /// <remarks/>
        public void GetUserNameAsync(string sessionID, int userID, object userState) {
            if ((this.GetUserNameOperationCompleted == null)) {
                this.GetUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserNameOperationCompleted);
            }
            this.InvokeAsync("GetUserName", new object[] {
                        sessionID,
                        userID}, this.GetUserNameOperationCompleted, userState);
        }
        
        private void OnGetUserNameOperationCompleted(object arg) {
            if ((this.GetUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserNameCompleted(this, new GetUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/GetUserAppsInfo3", RequestElementName="GetUserAppsInfo3", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="GetUserAppsInfo3Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserAppsInfo3Result")]
        public System.Data.DataSet GetUserAppsInfo(string sessionID, int userID) {
            object[] results = this.Invoke("GetUserAppsInfo", new object[] {
                        sessionID,
                        userID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAppsInfoAsync(string sessionID, int userID) {
            this.GetUserAppsInfoAsync(sessionID, userID, null);
        }
        
        /// <remarks/>
        public void GetUserAppsInfoAsync(string sessionID, int userID, object userState) {
            if ((this.GetUserAppsInfoOperationCompleted == null)) {
                this.GetUserAppsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAppsInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserAppsInfo", new object[] {
                        sessionID,
                        userID}, this.GetUserAppsInfoOperationCompleted, userState);
        }
        
        private void OnGetUserAppsInfoOperationCompleted(object arg) {
            if ((this.GetUserAppsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserAppsInfoCompleted(this, new GetUserAppsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsSsiUser1", RequestElementName="IsSsiUser1", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="IsSsiUser1Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsSsiUser1Result")]
        public bool IsSsiUser(string sessionID, string userName) {
            object[] results = this.Invoke("IsSsiUser", new object[] {
                        sessionID,
                        userName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsSsiUserAsync(string sessionID, string userName) {
            this.IsSsiUserAsync(sessionID, userName, null);
        }
        
        /// <remarks/>
        public void IsSsiUserAsync(string sessionID, string userName, object userState) {
            if ((this.IsSsiUserOperationCompleted == null)) {
                this.IsSsiUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsSsiUserOperationCompleted);
            }
            this.InvokeAsync("IsSsiUser", new object[] {
                        sessionID,
                        userName}, this.IsSsiUserOperationCompleted, userState);
        }
        
        private void OnIsSsiUserOperationCompleted(object arg) {
            if ((this.IsSsiUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsSsiUserCompleted(this, new IsSsiUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="IsSsiUser1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://146.243.13.169/SSO_WS/IsSsiUser2", RequestElementName="IsSsiUser2", RequestNamespace="http://146.243.13.169/SSO_WS/", ResponseElementName="IsSsiUser2Response", ResponseNamespace="http://146.243.13.169/SSO_WS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsSsiUser2Result")]
        public bool IsSsiUser(string sessionID, int userID) {
            object[] results = this.Invoke("IsSsiUser1", new object[] {
                        sessionID,
                        userID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsSsiUser1Async(string sessionID, int userID) {
            this.IsSsiUser1Async(sessionID, userID, null);
        }
        
        /// <remarks/>
        public void IsSsiUser1Async(string sessionID, int userID, object userState) {
            if ((this.IsSsiUser1OperationCompleted == null)) {
                this.IsSsiUser1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsSsiUser1OperationCompleted);
            }
            this.InvokeAsync("IsSsiUser1", new object[] {
                        sessionID,
                        userID}, this.IsSsiUser1OperationCompleted, userState);
        }
        
        private void OnIsSsiUser1OperationCompleted(object arg) {
            if ((this.IsSsiUser1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsSsiUser1Completed(this, new IsSsiUser1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://146.243.13.169/SSO_WS/")]
    public enum EECApp {
        
        /// <remarks/>
        NoApplication,
        
        /// <remarks/>
        eCCIMS,
        
        /// <remarks/>
        TQ,
        
        /// <remarks/>
        BRCManager,
        
        /// <remarks/>
        ProfessionalDevelopment,
        
        /// <remarks/>
        LicensingManager,
        
        /// <remarks/>
        EducatorRegistry,
        
        /// <remarks/>
        QRIS,
        
        /// <remarks/>
        QRISStatewide,
        
        /// <remarks/>
        KinderWait,
        
        /// <remarks/>
        ImproperPayment,
        
        /// <remarks/>
        ImproperPaymentFraud,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://146.243.13.169/SSO_WS/")]
    public enum Gender {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Female,
        
        /// <remarks/>
        Male,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://146.243.13.169/SSO_WS/")]
    public enum TermsConditions {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://146.243.13.169/SSO_WS/")]
    public enum SSOStatus {
        
        /// <remarks/>
        CreatedByAdmin,
        
        /// <remarks/>
        UserCreated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsGoodEmailAddressCompletedEventHandler(object sender, IsGoodEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsGoodEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsGoodEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsGoodUserNameCompletedEventHandler(object sender, IsGoodUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsGoodUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsGoodUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsGoodPasswordCompletedEventHandler(object sender, IsGoodPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsGoodPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsGoodPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsGoodPhoneNumberCompletedEventHandler(object sender, IsGoodPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsGoodPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsGoodPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void UpdateSessionHistoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetSessionIdCompletedEventHandler(object sender, GetSessionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSessionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSessionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsValidSessionCompletedEventHandler(object sender, IsValidSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserProfileCompletedEventHandler(object sender, GetUserProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserProfile1CompletedEventHandler(object sender, GetUserProfile1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfile1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfile1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserProfile2CompletedEventHandler(object sender, GetUserProfile2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfile2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfile2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserProfile_MultipleCompletedEventHandler(object sender, GetUserProfile_MultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserProfile_MultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserProfile_MultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AddNewSsiUserCompletedEventHandler(object sender, AddNewSsiUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewSsiUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewSsiUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AddNewSsiUser1CompletedEventHandler(object sender, AddNewSsiUser1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewSsiUser1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewSsiUser1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void UpdateSsiUserCompletedEventHandler(object sender, UpdateSsiUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSsiUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSsiUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void StartNewSessionCompletedEventHandler(object sender, StartNewSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartNewSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartNewSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void StartNewSession1CompletedEventHandler(object sender, StartNewSession1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartNewSession1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartNewSession1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void StartNewSessionByUsernamePasswordCompletedEventHandler(object sender, StartNewSessionByUsernamePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartNewSessionByUsernamePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartNewSessionByUsernamePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void EndSessionCompletedEventHandler(object sender, EndSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void DeActivateUserCompletedEventHandler(object sender, DeActivateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeActivateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeActivateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ActivateUserCompletedEventHandler(object sender, ActivateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserIDCompletedEventHandler(object sender, GetUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserID1CompletedEventHandler(object sender, GetUserID1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserID1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserID1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserNameCompletedEventHandler(object sender, GetUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetUserAppsInfoCompletedEventHandler(object sender, GetUserAppsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserAppsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserAppsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsSsiUserCompletedEventHandler(object sender, IsSsiUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsSsiUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsSsiUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IsSsiUser1CompletedEventHandler(object sender, IsSsiUser1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsSsiUser1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsSsiUser1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591