USE [GrantOnlineFY2016]
GO

/****** Object:  StoredProcedure [dbo].[uspGetAllCPPIProgramsForRDL]    Script Date: 11/7/2018 1:11:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[uspGetAllCPPIProgramsForRDL] @GrantApplicantId INT
AS 

	CREATE TABLE #tmpCPPIProgramInfo (
		SystemProviderId INT NOT NULL,
		GrantApplicantId INT NOT NULL,
		agencyname VARCHAR(100) NULL,
		amount MONEY NULL,			
		cboProgramType VARCHAR(4) NULL,
		ddlAccreditation VARCHAR(50) NULL,
		rbtnIsAccredited CHAR(1) NULL,
		rbtnIsCQIP CHAR(1) NULL,
		rbtnIsHeadStartProgram CHAR(1) NULL,
		rtbnIsProgramLicensed CHAR(1) NULL,
		rbtnScreenTool CHAR(1) NULL,
		rdoQRISLevel CHAR(1) NULL,
		txtAccreditationEarnDate VARCHAR(20) NULL,
		txtAccreditationExpDate VARCHAR(20) NULL,
		txtAccreditationNumber VARCHAR(20) NULL,
		txtAmericanIndianAlaskaPctCommunity VARCHAR(6) NULL,
		txtAmericanIndianAlaskaPctJune1 VARCHAR(6) NULL,
		txtAmericanIndianAlaskaPctMarch1 VARCHAR(6) NULL,		
		txtAsianPctCommunity VARCHAR(6) NULL,
		txtAsianPctJune1 VARCHAR(6) NULL,
		txtAsianPctMarch1 VARCHAR(6) NULL,		
		txtBiracialMultiPctCommunity VARCHAR(6) NULL,
		txtBiracialMultiPctJune1 VARCHAR(6) NULL,
		txtBiracialMultiPctMarch1 VARCHAR(6) NULL,		
		txtBlackAfricanPctCommunity VARCHAR(6) NULL,
		txtBlackAfricanPctJune1 VARCHAR(6) NULL,
		txtBlackAfricanPctMarch1 VARCHAR(6) NULL,		
		txtCQIPLastUpdated VARCHAR(20) NULL,
		txtCurriculaPlan varchar(max) NULL,
		txtDummy VARCHAR(100) NULL,
		txtEECProgramNumber VARCHAR(20) NULL,
		txtHawaiianPacificPctCommunity VARCHAR(6) NULL,
		txtHawaiianPacificPctJune1 VARCHAR(6) NULL,
		txtHawaiianPacificPctMarch1 VARCHAR(6) NULL,
		txtHispanicPctCommunity VARCHAR(6) NULL,
		txtHispanicPctJune1 VARCHAR(6) NULL,
		txtHispanicPctMarch1 VARCHAR(6) NULL,	
		txtNonHispanicPctCommunity VARCHAR(6) NULL,
		txtNonHispanicPctJune1 VARCHAR(6) NULL,
		txtNonHispanicPctMarch1 VARCHAR(6) NULL,
		txtOtherrRacePctCommunity VARCHAR(6) NULL,
		txtOtherRacePctJune1 VARCHAR(6) NULL,
		txtOtherRacePctMarch1 VARCHAR(6) NULL,		
		txtProgAddress1 VARCHAR(100) NULL,
		txtProgAddress2 VARCHAR(100) NULL,
		txtProgCity VARCHAR(100) NULL,
		txtProgContactName VARCHAR(100) NULL,
		txtProgEmail VARCHAR(100) NULL,
		txtProgFAX VARCHAR(20) NULL,
		txtProgPhone VARCHAR(20) NULL,
		txtProgramName VARCHAR(100) NULL,
		txtProgState CHAR(2) NULL,
		txtProgZipcode VARCHAR(10) NULL,
		txtQ1_1_1 VARCHAR(10) NULL,
		txtQ1_1_2 VARCHAR(10) NULL,
		txtQ1_1_3 VARCHAR(10) NULL,
		txtQ1_2_1 VARCHAR(10) NULL,
		txtQ1_2_2 VARCHAR(10) NULL,
		txtQ1_2_3 VARCHAR(10) NULL,
		txtQ1_3_1 VARCHAR(10) NULL,
		txtQ1_3_2 VARCHAR(10) NULL,
		txtQ1_3_3 VARCHAR(10) NULL,
		txtQ1_5_1 VARCHAR(10) NULL,		
		txtQ1_5_2 VARCHAR(10) NULL,
		txtQ1_5_3 VARCHAR(10) NULL,
		txtQ2_1_1 VARCHAR(10) NULL,
		txtQ2_1_2 VARCHAR(10) NULL,
		txtQ2_1_3 VARCHAR(10) NULL,
		txtQ2_1_4 VARCHAR(10) NULL,
		txtQ2_1_5 VARCHAR(10) NULL,
		txtQ2_1_6 VARCHAR(10) NULL,
		txtQ2_2_1 VARCHAR(10) NULL,
		txtQ2_2_2 VARCHAR(10) NULL,
		txtQ2_2_3 VARCHAR(10) NULL,
		txtQ2_2_4 VARCHAR(10) NULL,
		txtQ2_2_5 VARCHAR(10) NULL,
		txtQ2_2_6 VARCHAR(10) NULL,
		txtQ2_3_1 VARCHAR(10) NULL,
		txtQ2_3_2 VARCHAR(10) NULL,
		txtQ2_3_3 VARCHAR(10) NULL,
		txtQ2_3_4 VARCHAR(10) NULL,
		txtQ2_3_5 VARCHAR(10) NULL,
		txtQ2_3_6 VARCHAR(10) NULL,
		txtQ2_5_1 VARCHAR(10) NULL,
		txtQ2_5_2 VARCHAR(10) NULL,
		txtQ2_5_3 VARCHAR(10) NULL,
		txtQ2_5_4 VARCHAR(10) NULL,
		txtQ2_5_5 VARCHAR(10) NULL,
		txtQ2_5_6 VARCHAR(10) NULL,
		txtQ3_1_1 VARCHAR(10) NULL,
		txtQ3_1_2 VARCHAR(10) NULL,
		txtQ3_1_3 VARCHAR(10) NULL,
		txtQ3_2_1 VARCHAR(10) NULL,
		txtQ3_2_2 VARCHAR(10) NULL,
		txtQ3_2_3 VARCHAR(10) NULL,
		txtQ3_3_1 VARCHAR(10) NULL,
		txtQ3_3_2 VARCHAR(10) NULL,
		txtQ3_3_3 VARCHAR(10) NULL,
		txtQ3_5_1 VARCHAR(10) NULL,
		txtQ3_5_2 VARCHAR(10) NULL,
		txtQ3_5_3 VARCHAR(10) NULL,
		txtQ4_1_1 VARCHAR(10) NULL,
		txtQ4_1_2 VARCHAR(10) NULL,
		txtQ4_1_3 VARCHAR(10) NULL,
		txtQ4_2_1 VARCHAR(10) NULL,
		txtQ4_2_2 VARCHAR(10) NULL,
		txtQ4_2_3 VARCHAR(10) NULL,
		txtQ4_3_1 VARCHAR(10) NULL,
		txtQ4_3_2 VARCHAR(10) NULL,
		txtQ4_3_3 VARCHAR(10) NULL,
		txtQ4_5_1 VARCHAR(10) NULL,
		txtQ4_5_2 VARCHAR(10) NULL,
		txtQ4_5_3 VARCHAR(10) NULL,		
		txtQ9YesOption1 CHAR(1) NULL,
		txtQ9YesOption2 CHAR(1) NULL,
		txtQ9YesOption3 CHAR(1) NULL,
		txtQ9YesOption4 CHAR(1) NULL,
		txtQ9YesOption5 CHAR(1) NULL,
		txtScreenToolOther VARCHAR(100) NULL,
		txtUnspecifiedPctCommunity VARCHAR(6) NULL,
		txtUnspecifiedPctJune1 VARCHAR(6) NULL,
		txtUnspecifiedPctMarch1 VARCHAR(6) NULL,
		txtWhiteCaucasianPctCommunity VARCHAR(6) NULL,
		txtWhiteCaucasianPctJune1 VARCHAR(6) NULL,
		txtWhiteCaucasianPctMarch1 VARCHAR(6) NULL 
		)

    INSERT INTO #tmpCPPIProgramInfo
    (
        SystemProviderId,
        GrantApplicantId,
        agencyname,
        amount,
        cboProgramType,
        ddlAccreditation,
        rbtnIsAccredited,
        rbtnIsCQIP,
        rbtnIsHeadStartProgram,
        rtbnIsProgramLicensed,
        rbtnScreenTool,
        rdoQRISLevel,
        txtAccreditationEarnDate,
        txtAccreditationExpDate,
        txtAccreditationNumber,
        txtAmericanIndianAlaskaPctCommunity,
        txtAmericanIndianAlaskaPctJune1,
        txtAmericanIndianAlaskaPctMarch1,
        txtAsianPctCommunity,
        txtAsianPctJune1,
        txtAsianPctMarch1,
        txtBiracialMultiPctCommunity,
        txtBiracialMultiPctJune1,
        txtBiracialMultiPctMarch1,
        txtBlackAfricanPctCommunity,
        txtBlackAfricanPctJune1,
        txtBlackAfricanPctMarch1,
        txtCQIPLastUpdated,
        txtCurriculaPlan,
        txtDummy,
        txtEECProgramNumber,
        txtHawaiianPacificPctCommunity,
        txtHawaiianPacificPctJune1,
        txtHawaiianPacificPctMarch1,
        txtHispanicPctCommunity,
        txtHispanicPctJune1,
        txtHispanicPctMarch1,
        txtNonHispanicPctCommunity,
        txtNonHispanicPctJune1,
        txtNonHispanicPctMarch1,
        txtOtherrRacePctCommunity,
        txtOtherRacePctJune1,
        txtOtherRacePctMarch1,
        txtProgAddress1,
        txtProgAddress2,
        txtProgCity,
        txtProgContactName,
        txtProgEmail,
        txtProgFAX,
        txtProgPhone,
        txtProgramName,
        txtProgState,
        txtProgZipcode,
        txtQ1_1_1,
        txtQ1_1_2,
        txtQ1_1_3,
        txtQ1_2_1,
        txtQ1_2_2,
        txtQ1_2_3,
        txtQ1_3_1,
        txtQ1_3_2,
        txtQ1_3_3,
        txtQ1_5_1,
        txtQ1_5_2,
        txtQ1_5_3,
        txtQ2_1_1,
        txtQ2_1_2,
        txtQ2_1_3,
        txtQ2_1_4,
        txtQ2_1_5,
        txtQ2_1_6,
        txtQ2_2_1,
        txtQ2_2_2,
        txtQ2_2_3,
        txtQ2_2_4,
        txtQ2_2_5,
        txtQ2_2_6,
        txtQ2_3_1,
        txtQ2_3_2,
        txtQ2_3_3,
        txtQ2_3_4,
        txtQ2_3_5,
        txtQ2_3_6,
        txtQ2_5_1,
        txtQ2_5_2,
        txtQ2_5_3,
        txtQ2_5_4,
        txtQ2_5_5,
        txtQ2_5_6,
        txtQ3_1_1,
        txtQ3_1_2,
        txtQ3_1_3,
        txtQ3_2_1,
        txtQ3_2_2,
        txtQ3_2_3,
        txtQ3_3_1,
        txtQ3_3_2,
        txtQ3_3_3,
        txtQ3_5_1,
        txtQ3_5_2,
        txtQ3_5_3,
        txtQ4_1_1,
        txtQ4_1_2,
        txtQ4_1_3,
        txtQ4_2_1,
        txtQ4_2_2,
        txtQ4_2_3,
        txtQ4_3_1,
        txtQ4_3_2,
        txtQ4_3_3,
        txtQ4_5_1,
        txtQ4_5_2,
        txtQ4_5_3,
        txtQ9YesOption1,
        txtQ9YesOption2,
        txtQ9YesOption3,
        txtQ9YesOption4,
        txtQ9YesOption5,
        txtScreenToolOther,
        txtUnspecifiedPctCommunity,
        txtUnspecifiedPctJune1,
        txtUnspecifiedPctMarch1,
        txtWhiteCaucasianPctCommunity,
        txtWhiteCaucasianPctJune1,
        txtWhiteCaucasianPctMarch1
    )
	EXEC dbo.uspGetAllCPPIProgramsNew @GrantApplicantId


	SELECT SystemProviderId,
        GrantApplicantId,
        txtProgramName,
        cboProgramType,
        ddlAccreditation,
        rbtnIsAccredited,
        rbtnIsCQIP,
        txtProgContactName,
        txtProgAddress1,
        txtProgAddress2,
        txtProgCity,
        txtProgState,
        txtProgZipcode,
        txtProgPhone,
        txtProgFAX,
        txtProgEmail,
        rtbnIsProgramLicensed,
        txtEECProgramNumber,
        rbtnIsHeadStartProgram,
        txtAccreditationEarnDate,
        txtAccreditationExpDate,
        txtAccreditationNumber,
        txtCurriculaPlan,
        rdoQRISLevel,
        txtCQIPLastUpdated,
        rbtnScreenTool,
        txtQ9YesOption1,
        txtQ9YesOption2,
        txtQ9YesOption3,
        txtQ9YesOption4,
        txtQ9YesOption5,
        txtScreenToolOther,
        txtHispanicPctCommunity,
        txtHispanicPctMarch1,
        txtHispanicPctJune1,
        txtNonHispanicPctCommunity,
        txtNonHispanicPctMarch1,
        txtNonHispanicPctJune1,
        txtAmericanIndianAlaskaPctCommunity,
        txtAmericanIndianAlaskaPctMarch1,
        txtAmericanIndianAlaskaPctJune1,
        txtAsianPctCommunity,
        txtAsianPctMarch1,
        txtAsianPctJune1,
        txtBlackAfricanPctCommunity,
        txtBlackAfricanPctMarch1,
        txtBlackAfricanPctJune1,
        txtHawaiianPacificPctCommunity,
        txtHawaiianPacificPctMarch1,
        txtHawaiianPacificPctJune1,
        txtWhiteCaucasianPctCommunity,
        txtWhiteCaucasianPctMarch1,
        txtWhiteCaucasianPctJune1,
        txtBiracialMultiPctCommunity,
        txtBiracialMultiPctMarch1,
        txtBiracialMultiPctJune1,
        txtOtherrRacePctCommunity,
        txtOtherRacePctMarch1,
        txtOtherRacePctJune1,
        txtUnspecifiedPctCommunity,
        txtUnspecifiedPctMarch1,
        txtUnspecifiedPctJune1,
        txtQ1_1_1,
        txtQ1_2_1,
        txtQ1_3_1,
        txtQ1_5_1,
        txtQ1_1_2,
        txtQ1_2_2,
        txtQ1_3_2,
        txtQ1_5_2,
        txtQ1_1_3,
        txtQ1_2_3,
        txtQ1_3_3,
        txtQ1_5_3,
        txtQ2_1_1,
        txtQ2_1_2,
        txtQ2_1_3,
        txtQ2_1_4,
        txtQ2_1_5,
        txtQ2_1_6,
        txtQ2_2_1,
        txtQ2_2_2,
        txtQ2_2_3,
        txtQ2_2_4,
        txtQ2_2_5,
        txtQ2_2_6,
        txtQ2_3_1,
        txtQ2_3_2,
        txtQ2_3_3,
        txtQ2_3_4,
        txtQ2_3_5,
        txtQ2_3_6,
        txtQ2_5_1,
        txtQ2_5_2,
        txtQ2_5_3,
        txtQ2_5_4,
        txtQ2_5_5,
        txtQ2_5_6,
        txtQ3_1_1,
        txtQ3_1_2,
        txtQ3_1_3,
        txtQ3_2_1,
        txtQ3_2_2,
        txtQ3_2_3,
        txtQ3_3_1,
        txtQ3_3_2,
        txtQ3_3_3,
        txtQ3_5_1,
        txtQ3_5_2,
        txtQ3_5_3,
        txtQ4_1_1,
        txtQ4_1_2,
        txtQ4_1_3,
        txtQ4_2_1,
        txtQ4_2_2,
        txtQ4_2_3,
        txtQ4_3_1,
        txtQ4_3_2,
        txtQ4_3_3,
        txtQ4_5_1,
        txtQ4_5_2,
        txtQ4_5_3
	FROM #tmpCPPIProgramInfo

	DROP TABLE #tmpCPPIProgramInfo


GO

